//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.16 at 02:56:25 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sal.jcu.edu.au/schemas/pluginsConfig", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jcu.sal.config.plugins.xml;
