//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.15 at 09:47:13 PM EST 
//


package jcu.sal.config.plugins.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConfigPlugins" type="{http://sal.jcu.edu.au/schemas/pluginsConfig}ConfigPluginsType"/>
 *         &lt;element name="ProtocolPlugins" type="{http://sal.jcu.edu.au/schemas/pluginsConfig}ProtocolPluginsType"/>
 *         &lt;element name="EndPointPlugins" type="{http://sal.jcu.edu.au/schemas/pluginsConfig}EndPointPluginsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "configPlugins",
    "protocolPlugins",
    "endPointPlugins"
})
@XmlRootElement(name = "SalPlugins")
public class SalPlugins {

    @XmlElement(name = "ConfigPlugins", required = true)
    protected ConfigPluginsType configPlugins;
    @XmlElement(name = "ProtocolPlugins", required = true)
    protected ProtocolPluginsType protocolPlugins;
    @XmlElement(name = "EndPointPlugins", required = true)
    protected EndPointPluginsType endPointPlugins;

    /**
     * Gets the value of the configPlugins property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigPluginsType }
     *     
     */
    public ConfigPluginsType getConfigPlugins() {
        return configPlugins;
    }

    /**
     * Sets the value of the configPlugins property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigPluginsType }
     *     
     */
    public void setConfigPlugins(ConfigPluginsType value) {
        this.configPlugins = value;
    }

    /**
     * Gets the value of the protocolPlugins property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolPluginsType }
     *     
     */
    public ProtocolPluginsType getProtocolPlugins() {
        return protocolPlugins;
    }

    /**
     * Sets the value of the protocolPlugins property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolPluginsType }
     *     
     */
    public void setProtocolPlugins(ProtocolPluginsType value) {
        this.protocolPlugins = value;
    }

    /**
     * Gets the value of the endPointPlugins property.
     * 
     * @return
     *     possible object is
     *     {@link EndPointPluginsType }
     *     
     */
    public EndPointPluginsType getEndPointPlugins() {
        return endPointPlugins;
    }

    /**
     * Sets the value of the endPointPlugins property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndPointPluginsType }
     *     
     */
    public void setEndPointPlugins(EndPointPluginsType value) {
        this.endPointPlugins = value;
    }

}
