//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.28 at 05:18:40 PM EST 
//


package jcu.sal.common.cml.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jcu.sal.common.cml.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jcu.sal.common.cml.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CommandDescription.Streaming.Bounds }
     * 
     */
    public CommandDescription.Streaming.Bounds createCommandDescriptionStreamingBounds() {
        return new CommandDescription.Streaming.Bounds();
    }

    /**
     * Create an instance of {@link Argument.Bounds }
     * 
     */
    public Argument.Bounds createArgumentBounds() {
        return new Argument.Bounds();
    }

    /**
     * Create an instance of {@link CommandDescription.Arguments }
     * 
     */
    public CommandDescription.Arguments createCommandDescriptionArguments() {
        return new CommandDescription.Arguments();
    }

    /**
     * Create an instance of {@link Argument.List.Item }
     * 
     */
    public Argument.List.Item createArgumentListItem() {
        return new Argument.List.Item();
    }

    /**
     * Create an instance of {@link CommandDescription }
     * 
     */
    public CommandDescription createCommandDescription() {
        return new CommandDescription();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link CommandDescriptions }
     * 
     */
    public CommandDescriptions createCommandDescriptions() {
        return new CommandDescriptions();
    }

    /**
     * Create an instance of {@link CommandDescription.Streaming }
     * 
     */
    public CommandDescription.Streaming createCommandDescriptionStreaming() {
        return new CommandDescription.Streaming();
    }

    /**
     * Create an instance of {@link Argument.List }
     * 
     */
    public Argument.List createArgumentList() {
        return new Argument.List();
    }

    /**
     * Create an instance of {@link Argument }
     * 
     */
    public Argument createArgument() {
        return new Argument();
    }

}
