//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.28 at 05:18:40 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sal.jcu.edu.au/schemas/CML", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jcu.sal.common.cml.xml;
